### PR TITLE
Design/branch

### PR DESCRIPTION
**Pull request by ANTOINE1128**
In this PR I have done the following :
- Created a new directory called Components.
- Inside components, create a new Calculator.js file.
- In Calculator.js, I created a React component that matches the design:
- Implemented the design only (JSX and CSS)
- Used functional components

### CODE REVIEW

**Review by TedLivist — COMMENTED** [review]
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @ANTOINE1128,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### The following links in your Table of Contents are broken: **Install, Usage, Run tests, Deployment, Live Demo**. Kindly fix them by adding the corresponding sections. You can remove the live demo link unless you have a valid deployment link.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ANTOINE1128** [comment]
@TedLivist I am sorry but I did not understand why my code is invalid ?

**Comment by TedLivist** [comment]
@ANTOINE1128 in your README, all the links for the sections I listed are broken. You should add their sections - we should not have broken links on the README.

**Comment by ANTOINE1128** [comment]
thank you so much for the review and for the clarification  @TedLivist

**Review by TuyishimireEric — APPROVED** [review]
# Status: APPROVED 🟢  
### Hi  @ANTOINE1128  👋 👋 

#### I'm @TuyishimireEric, Your code reviewer,
Good job on implementing the project requirements! 🥇 
done

Your project is complete!  There is nothing else to say other than... it's time to merge it 🦾  
Congratulations! 🎉

## Highlights
✔ The app is created with **Create React App**👍
✔ Developed React component that holds the core functionality: a calculator. :+1:
✔ Descriptive PR👍

### Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/enus/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
